draft for status types and defintiions
vcstuff/draft-looker-jwt-cwt-status-list pull request #17
Opened 2023-05-23 16:45 UTC by paulbastian

2023-05-24 10:42 UTC, paulbastian commented
Micha proposed to change REVOKED to INVALID, as it gives less intention whether this is a permanent state and the issuers could reflect a suspension also with a 1bit size status list as well

2023-06-06 19:53 UTC, Sakurann requested changes
sorry, I am not onboard with giving the issuers the complete freedom to define their own status values. for the interop purposes, the valid and invalid values MUST always be the same. ie 0 is always valid and 1 is always invalid. (or vice versa - that I do not care). so when the bit size is bigger than 2, the first bite is always valid/invalid and from the second bit, it can be suspended, etc.

2023-06-06 20:51 UTC, tplooker commented
I'm in agreement with Kristina, the more I look at this the more I think we should have one possible enumeration of statuses rather than allowing every issuer to define their own, the question then becomes how big that set needs to be as it controls how many bits are allocated to each credential in the status list.

2023-06-07 05:29 UTC, paulbastian commented
I'm fine with defining the first bit as valid/invalid. I think providing the option for additional bits offers benefits with acceptable tradeoffs

2023-06-07 12:18 UTC, paulbastian commented
I've made some changes, please recheck @tplooker @Sakurann

2023-06-09 06:38 UTC, Sakurann commented
umm I thought we agreed to remove the concept of the "typ" attribute.. so no `revocation-list` and no `suspention-status-list`.

2023-06-09 09:04 UTC, tplooker commented
Yeah that was captured here @Sakurann https://github.com/vcstuff/draft-looker-jwt-cwt-status-list/pull/20#issuecomment-1581385983

2023-06-09 10:43 UTC, tlodderstedt commented
> umm I thought we agreed to remove the concept of the "typ" attribute.. so no `revocation-list` and no `suspention-status-list`.

But I assume the Status List Token will have a `typ` JOSE header to properly distinguish it from other JWTs, right?

2023-06-13 05:49 UTC, Sakurann commented
@tlodderstedt typo on my end. yes, JWT should be typed (`typ` claim present), the current spec also introduces a `type` body claim as far as I can see, which is what I am not in agreement with.

2023-06-13 05:50 UTC, Sakurann commented
@tplooker I am confused. so the idea is to merge this PR and then remove the "type" JWT claim in PR #20?

2023-06-13 05:52 UTC, paulbastian commented
There are separate issues already open and things are being resolved in the other PR. This one is only about introduction and renaming

2023-06-13 19:09 UTC, tplooker commented on draft-looker-jwt-cwt-status-list.md
> +2. The claim value object MUST contain an "idx" (index) attribute with a numberic based value that represents the index to check for status information in the status list for the current JWT. The val
```suggestion
2. The claim value object MUST contain an "idx" (index) attribute with a numeric based value that represents the index to check for status information in the status list for the current JWT. The value of this attribute MUST be a non-negative number, containing a value of zero or greater. Refer to xx for details on the validation procedure.
```

2023-06-13 19:10 UTC, Sakurann approved these changes
I am a little confused with calling "VALID", "INVALID" Status List `type`, but agreed this should be merged

2023-06-14 21:45 UTC, paulbastian commented
@tplooker ready for merge

2023-06-15 07:06 UTC, merged