ascii art for bit and byte ordering
vcstuff/draft-looker-jwt-cwt-status-list pull request #29
Opened 2023-06-15 15:32 UTC by paulbastian

2023-06-15 15:33 UTC, paulbastian commented
after writing this I figured out changing the byte ordering, i.e. starting with byte 0 on the left might be a little more intuitive?

2023-06-16 03:07 UTC, tplooker commented
> after writing this I figured out changing the byte ordering, i.e. starting with byte 0 on the left might be a little more intuitive?

Yeah with fresh eyes I definately think that would be better.

2023-06-16 08:08 UTC, paulbastian commented
reversed byte order and added the index to the ascii art

2023-06-16 11:03 UTC, c2bo requested changes
More compact version

2023-06-16 11:03 UTC, c2bo commented on draft-looker-jwt-cwt-status-list.md
> +~~~
```suggestion
byte             0                  1                  2
bit       7 6 5 4 3 2 1 0    7 6 5 4 3 2 1 0    7 6 5 4 3 2 1 0
         +-+-+-+-+-+-+-+-+  +-+-+-+-+-+-+-+-+  +-+-+-+-+-+-+-+-+
values   |1|1|0|0|1|0|0|1|  |0|1|0|0|0|1|0|0|  |1|1|1|1|1|0|0|1|
         +-+-+-+-+-+-+-+-+  +-+-+-+-+-+-+-+-+  +-+-+-+-+-+-+-+-+
          \ / \ / \ / \ /    \ / \ / \ / \ /    \ / \ / \ / \ /
status     3   0   2   1      1   0   1   0      3   3   2   1
index      3   2   1   0      7   6   5   4      11  10  9   8
           \___________/      \___________/      \___________/
                0xC9               0x44               0xF9
```

2023-06-16 11:44 UTC, c2bo approved these changes

2023-06-17 06:21 UTC, tplooker approved these changes

2023-06-17 06:21 UTC, merged